---
title: "Untitled"
author: "Itamar Caspi"
date: "23 11 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(readxl)
library(lpirfs)
library(hrbrthemes)
library(RcppRoll)
library(showtext)
library(latex2exp)
library(paletteer)
```

```{r}
showtext_auto()
font_add_google("Gentium Book Basic", "book")
```


## Read data
```{r}
df_raw <- 
  read_tsv("data/data_new.txt")

df_rr  <- 
  read_xlsx("data/rr-euro.xlsx") %>%
  mutate(date = ymd(Date)) %>% 
  rename(rr = PX_BID) %>% 
  select(-Date)

df_opt <- 
  read_xlsx("data/sd-opt-eurodollar.xlsx") %>%
  mutate(date = ymd(Date)) %>% 
  rename(opt = PX_BID) %>% 
  select(-Date)

df_quant <- 
  read_xlsx("data/data_quantities.xlsx") %>%
  mutate(date   = ymd(date))
```

## Parameters
```{r}
hor     <- 100  # irf horizon
vol_win <- 20    # volatility window
```

## Processing
```{r}
df <- 
  df_raw %>% 
  mutate(
    date    = dmy(Date),
    ly      = 100 * log(closing_rate),
    dy      = ly - lag(ly, 1),
    u_fxi   = 100 * return_3,
    u1      = 100 * log(f_inv_prox / lag(closing_rate, 1)),
    u3      = 100 * log(closing_rate / l_inv_prox),
    vol     = roll_sdr(dy, vol_win),
    vol_l   = lag(vol, 1),
    bas     = 100 * (ASK - BID) / MID,
    bas_l   = lag(bas, 1),
    d_0911  = if_else(date <= ymd("2011-12-31"), 1, 0),
    d_1317  = if_else(date >= ymd("2013-01-01"), 1, 0)
  ) %>% 
  filter(between(date, ymd("2009-09-08"), ymd("2017-04-28"))) %>% 
  replace_na(list(u_fxi = 0, u1 = 0, u3 = 0)) %>% 
  mutate(d_fxi   = if_else(u_fxi != 0, "With FXI", "Without FXI")) %>% 
  select(
    date, ly, dy, u_fxi, u1, u3, d_fxi, vol_l, bas_l, starts_with("d_")
  ) %>% 
  left_join(df_rr) %>% 
  left_join(df_opt) %>% 
  left_join(df_quant) %>% 
  mutate(
    sum = if_else(is.na(sum), 0, sum),
    sum = sum / 1e6
  )
```

## Shocks summary stats
```{r}
df %>%
  select(date, dy, u1, u_fxi, u3) %>%
  filter(u_fxi != 0) %>%
  pivot_longer(-date, names_to = "shock", values_to = "value") %>%
  ggplot(aes(value, fill = shock)) +
  geom_histogram(bins = 50) +
  geom_vline(aes(xintercept = 0)) +
  # scale_fill_paletteer_d("ggthemes::Color_Blind") +
  scale_fill_grey() +
  facet_wrap(~ shock, nrow = 2) +
  theme_ipsum(base_family = "book") +
  theme(
    axis.title.x = element_text(size=rel(1.3)),
    axis.title.y = element_text(size=rel(1.3)),
    legend.text = element_text(size=rel(1)),
    legend.position = "none"
  ) +
  labs(
    x = "return"
  )
```

```{r}
df %>% 
  select(dy, d_fxi) %>% 
  ggplot(aes(dy, after_stat(density), color = factor(d_fxi))) +
  geom_density(size = 1) +
  geom_vline(aes(xintercept = 0)) +
  # scale_fill_paletteer_d("ggthemes::Color_Blind") +
  scale_color_grey() +
  # facet_wrap(~ d_fxi) +
  theme_ipsum(base_family = "book") +
  theme(legend.position = "bottom") +
  labs(
    x = "return",
    fill = "",
    color = ""
  ) +
  theme(
    axis.title.x = element_text(size=rel(1.3)),
    axis.title.y = element_text(size=rel(1.3)),
    legend.text = element_text(size=rel(0.85)),
    legend.position = "bottom"
  )
```


```{r}
df_shocks <-
  df %>%
  select(dy, u1, u_fxi, u3) %>%
  filter(u_fxi != 0)

df_shocks %>%
  skim()

df_shocks %>%
  select(-dy) %>%
  cor()

df_shocks %>%
  ggplot(aes(u1, u_fxi)) +
  geom_point(color = "#3E4A89", size = 2, alpha = 0.5) +
  geom_hline(aes(yintercept = 0)) +
  geom_vline(aes(xintercept = 0)) +
  theme_ipsum() +
  labs(
    x = TeX("$u_{1t}$"),
    y = TeX("$FXI_t$")
  )
```


```{r}
df %>%
  filter(sum != 0) %>%
  mutate(u_fxi_sum = u_fxi / sum) %>%
  lm(u_fxi_sum ~ sum + I(sum^2) + I(sum^3), data = .) %>%
  tidy()

df %>%
  ggplot(aes(sum, u_fxi)) +
  geom_point()
```

